name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: vcpkg build
      uses: johnwason/vcpkg-action@v6
      id: vcpkg
      with:
        manifest-dir: ${{ github.workspace }} # Set to directory containing vcpkg.json
        token: ${{ github.token }}
        triplet: x64-linux-release
      # debugging
    # - name: Setup upterm session
      # uses: lhotari/action-upterm@v1

    - name: build
      run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 && cd build && make && cd - && echo "successfully built"

    - name: test
      run: make ci-tests

    - name: Run Clang Format and Clang Tidy
      uses: cpp-linter/cpp-linter-action@v2.13.4
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        database: build/
        files-changed-only: false
        format-review: false
        ignore: 'build|cmake-modules|docker'
        passive-reviews: true
        step-summary: true
        style: 'file'
        tidy-checks: ''
        thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
        version: 19
